
name: django-quant-trader
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - django=4.1
  - pip
  - pip:
    - celery==5.2.7
    - billiard==3.6.4.0
    - kombu==5.2.4
    - amqp==5.1.1
    - sqlalchemy
    - simplejson
    - requests
    - cryptography
    - pytz
    - urllib3
    - asgiref
    - brotli
    - sqlparse
    - typing-extensions
    - redis  
