# Generated by Django 5.0.7 on 2024-09-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UpbitData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.IntegerField()),
                ('recovered', models.BooleanField(default=False)),
                ('market', models.CharField(max_length=10)),
                ('date_time', models.DateTimeField()),
                ('opening_price', models.FloatField()),
                ('high_price', models.FloatField()),
                ('low_price', models.FloatField()),
                ('closing_price', models.FloatField()),
                ('acc_price', models.FloatField()),
                ('acc_volume', models.FloatField()),
            ],
            options={
                'ordering': ['date_time'],
                'unique_together': {('period', 'market', 'date_time')},
            },
        ),
    ]
