# Generated by Django 4.1.7 on 2024-10-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_provider', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upbitdata',
            name='date_time',
            field=models.DateTimeField(db_index=True),
        ),
    ]
