# Generated by Django 4.2.14 on 2024-10-19 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_provider", "0003_alter_upbitdata_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="upbitdata",
            name="recovered",
        ),
        migrations.AlterField(
            model_name="upbitdata",
            name="acc_price",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="upbitdata",
            name="acc_volume",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="upbitdata",
            name="closing_price",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="upbitdata",
            name="high_price",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="upbitdata",
            name="low_price",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="upbitdata",
            name="opening_price",
            field=models.FloatField(null=True),
        ),
    ]
